# Generated by Django 6.0.5 on 2026-05-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('world', models.CharField(choices=[('ocean', 'Web Ocean'), ('space', 'Code Space'), ('matrix', 'Binary Matrix'), ('cloud', 'Cloud City')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='characters/')),
                ('is_default', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
