# Generated by Django 6.0.5 on 2026-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='worlds_unlocked',
            field=models.IntegerField(default=1),
        ),
    ]
