# Generated by Django 6.0.5 on 2026-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
